# Generated by Django 4.2.22 on 2025-12-05 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('college', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configurable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(null=True, upload_to=events.models.event_file_path)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('registration', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('event_date', models.DateField()),
                ('event_date_end', models.DateField()),
                ('event_time', models.TimeField()),
                ('event_time_end', models.TimeField()),
                ('location', models.TextField()),
                ('extra_information', models.TextField(blank=True, null=True)),
                ('extra_information_company', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, upload_to=events.models.event_advert_path)),
                ('published', models.CharField(max_length=3)),
                ('invitees', models.CharField(choices=[('1', 'Students Only'), ('2', 'Company Representatives Only'), ('3', 'Both Students and Company Representatives')], max_length=1)),
                ('company_organized', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='college.collegecampus')),
            ],
        ),
        migrations.CreateModel(
            name='EventCompanyRSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.CharField(default='No', max_length=3)),
                ('approved', models.CharField(default='No', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistrationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EventRSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend', models.CharField(default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvp_students', to='events.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvp_events', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistrationFormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('choice', models.CharField(blank=True, choices=[('one', 'one'), ('many', 'many')], default='one', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('required', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3)),
                ('question_number', models.PositiveIntegerField(null=True)),
                ('upload_file', models.FileField(blank=True, null=True, upload_to=events.models.event_file_path)),
                ('registration_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='events.eventregistrationform')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_form_questions', to='configurable.questiontype')),
            ],
        ),
        migrations.AddField(
            model_name='eventregistrationform',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_forms', to='events.eventtype'),
        ),
        migrations.CreateModel(
            name='EventRegistrationCompanyAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=256)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='events.eventregistrationformquestion')),
                ('registration_form_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_form_answers', to='events.eventcompanyrsvp')),
            ],
        ),
        migrations.CreateModel(
            name='EventMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Video Link', 'Video Link'), ('image', 'image'), ('PDF file', 'PDF file')], max_length=10)),
                ('image', models.ImageField(blank=True, upload_to=events.models.event_file_path)),
                ('file', models.FileField(blank=True, upload_to=events.models.event_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='events.event')),
            ],
        ),
        migrations.AddField(
            model_name='eventcompanyrsvp',
            name='registration_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_forms', to='events.eventregistrationform'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_form', to='events.eventregistrationform'),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventtype'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.TextField()),
                ('published', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_announcement', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
