# Generated by Django 4.2.22 on 2025-12-05 09:10

import college.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_nursing.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configurable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CohortRegistrationCompulsoryProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weights', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CohortRegistrationPeriodEducationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_week', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility_type', models.CharField(max_length=3, null=True)),
                ('time_period', models.CharField(choices=[('Night', 'Night'), ('Day', 'Day')], max_length=5, null=True)),
            ],
            options={
                'ordering': ['academic_week'],
            },
        ),
        migrations.CreateModel(
            name='CohortRegistrationPeriodModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance_year_mark', models.PositiveIntegerField()),
                ('summative_weight', models.PositiveIntegerField()),
                ('assignment_weight', models.PositiveIntegerField(default=0)),
                ('test_weight', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CohortRegistrationPeriodModuleFormative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=20)),
                ('weight', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CohortRegistrationPeriodModuleModerationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('moderators_feedback', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CohortRegistrationPeriodModuleModerationReportAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Applicable', 'Not Applicable')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CohortRegistrationPeriodModuleRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('time', models.TimeField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CohortRegistrationProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compulsory', models.CharField(default='No', max_length=3)),
                ('weights', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinical_facilitator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedure_clinical_facilitator', to=settings.AUTH_USER_MODEL)),
                ('clinical_facilitator_demonstration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedure_clinical_facilitator_demonstration', to=settings.AUTH_USER_MODEL)),
                ('co_assessor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedure_co_assessor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-weights'],
            },
        ),
        migrations.CreateModel(
            name='CohortRegistrationProcedureSummative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weights', models.PositiveIntegerField(default=0)),
                ('assessor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summative_procedure_lecturer', to=settings.AUTH_USER_MODEL)),
                ('clinical_facilitator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summative_procedure_clinical_facilitator', to=settings.AUTH_USER_MODEL)),
                ('co_assessor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summative_procedure_co_assessor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeCampus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('physical_address_1', models.CharField(max_length=100)),
                ('physical_address_2', models.CharField(max_length=100)),
                ('physical_address_3', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('postal_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='college_branches', to='configurable.suburb')),
            ],
        ),
        migrations.CreateModel(
            name='EducationPlanYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('academic_week_start', models.PositiveSmallIntegerField()),
                ('finalized', models.CharField(default='No', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=college.models.update_file_path)),
            ],
        ),
        migrations.CreateModel(
            name='EducationPlanYearSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('education_plan_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='college.educationplanyear')),
            ],
        ),
        migrations.CreateModel(
            name='EducationPlanYearSectionWeekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='HealthCareFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=5)),
                ('physical_address_1', models.CharField(max_length=100)),
                ('physical_address_2', models.CharField(max_length=100)),
                ('physical_address_3', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('Primary Health Care', 'Primary Health Care'), ('Hospital', 'Hospital')], max_length=22, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('postal_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_care_facilities', to='configurable.suburb')),
            ],
        ),
        migrations.CreateModel(
            name='LearningProgramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme_name', models.CharField(max_length=100)),
                ('programme_code', models.CharField(max_length=10)),
                ('total_credits', models.PositiveIntegerField()),
                ('duration', models.PositiveIntegerField()),
                ('active', models.CharField(default='Yes', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearningProgrammeCohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('student_cards', models.FileField(blank=True, null=True, upload_to=college.models.update_filename)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('learning_programme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cohorts', to='college.learningprogramme')),
            ],
        ),
        migrations.CreateModel(
            name='LearningProgrammeCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learning_programme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competencies', to='college.learningprogramme')),
            ],
        ),
        migrations.CreateModel(
            name='LearningProgrammeELO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.PositiveIntegerField()),
                ('learning_programme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elos', to='college.learningprogramme')),
            ],
        ),
        migrations.CreateModel(
            name='LearningProgrammeModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=100)),
                ('module_code', models.CharField(max_length=10)),
                ('credits', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module_type', models.CharField(choices=[('Core', 'Core'), ('Fundamental', 'Fundamental')], max_length=15, null=True)),
                ('theory_credits', models.PositiveIntegerField(default=0)),
                ('wil_credits', models.PositiveIntegerField(default=0)),
                ('theory_hours', models.PositiveIntegerField(default=0)),
                ('wil_hours', models.PositiveIntegerField(default=0)),
                ('entrance_year_mark', models.PositiveIntegerField(default=0)),
                ('summative_weight', models.PositiveIntegerField(default=0)),
                ('assignment_weight', models.PositiveIntegerField(default=0)),
                ('test_weight', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('learning_programme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='college.learningprogramme')),
                ('nqf_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='configurable.nqflevel')),
            ],
        ),
        migrations.CreateModel(
            name='LearningProgrammeModuleStudyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_unit_name', models.CharField(max_length=100)),
                ('study_unit_code', models.CharField(max_length=10)),
                ('credits', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_units', to='college.learningprogrammemodule')),
            ],
        ),
        migrations.CreateModel(
            name='LearningProgrammePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20)),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learning_programme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periods', to='college.learningprogramme')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='LearningProgrammePeriodRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learning_programme_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='college.learningprogrammeperiod')),
            ],
        ),
        migrations.CreateModel(
            name='LearningProgrammePeriodRegistrationModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance_year_mark', models.PositiveIntegerField()),
                ('summative_weight', models.PositiveIntegerField()),
                ('assignment_weight', models.PositiveIntegerField(default=0)),
                ('test_weight', models.PositiveIntegerField(default=0)),
                ('learning_programme_period_registration_period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='college.learningprogrammeperiodregistration')),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registeration_modules', to='college.learningprogrammemodule')),
            ],
        ),
        migrations.CreateModel(
            name='LearningProgrammeSimulationTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learning_programme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='themes', to='college.learningprogramme')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('staff_number', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=15)),
                ('active', models.CharField(default='Yes', max_length=3)),
                ('signature', models.FileField(null=True, upload_to=college.models.staff_profile_signature_file_path, validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg', 'png']), django_nursing.validators.validate_file_size])),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('college_campus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='college.collegecampus')),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='configurable.gender')),
                ('race', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='configurable.race')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('active', models.CharField(default='No', max_length=3)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_periods', to='configurable.registrationblockcode')),
            ],
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=15)),
                ('active', models.CharField(default='Yes', max_length=3)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderator', to='configurable.gender')),
                ('race', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderator', to='configurable.race')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='LPRegistrationPeriodModuleFormative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=20)),
                ('weight', models.PositiveIntegerField()),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formative', to='college.learningprogrammeperiodregistrationmodule')),
            ],
        ),
        migrations.CreateModel(
            name='LearningProgrammeSimulationThemeActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='college.learningprogrammesimulationtheme')),
            ],
        ),
        migrations.CreateModel(
            name='LearningProgrammePeriodWILRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('credits', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discipline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wil_requirements', to='configurable.discipline')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wil_requirements', to='college.learningprogrammeperiod')),
            ],
        ),
        migrations.CreateModel(
            name='LearningProgrammePeriodWILBlockHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('credits', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block_hours', to='configurable.progarmmeblock')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_hours', to='college.learningprogrammeperiod')),
            ],
        ),
        migrations.CreateModel(
            name='LearningProgrammePeriodTimeTableSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_sessions', to=settings.AUTH_USER_MODEL)),
                ('learning_programme_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_sessions', to='college.learningprogrammeperiod')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='learningprogrammeperiodregistration',
            name='registration_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='college.registrationperiod'),
        ),
        migrations.CreateModel(
            name='LearningProgrammePeriodModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period', to='college.learningprogrammemodule')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='college.learningprogrammeperiod')),
            ],
        ),
        migrations.CreateModel(
            name='LearningProgrammePeriodModerationCriteriaWIL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.TextField()),
                ('question_type', models.CharField(choices=[('Note', 'Note'), ('Heading', 'Heading'), ('Question', 'Question')], default='Question', max_length=10)),
                ('number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learning_programme_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_criteria_wil', to='college.learningprogrammeperiod')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_criteria_wil', to='accounts.role')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='LearningProgrammePeriodModerationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.TextField()),
                ('question_type', models.CharField(choices=[('Note', 'Note'), ('Heading', 'Heading'), ('Question', 'Question')], default='Question', max_length=10)),
                ('number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learning_programme_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_criteria', to='college.learningprogrammeperiod')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_criteria', to='accounts.role')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='LearningProgrammeModuleStudyUnitSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=100)),
                ('section_code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('study_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_unit_sections', to='college.learningprogrammemodulestudyunit')),
            ],
        ),
        migrations.CreateModel(
            name='LearningProgrammeModulePrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prerequisites', to='college.learningprogrammemodule')),
                ('prerequisite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postrequisites', to='college.learningprogrammemodule')),
            ],
        ),
        migrations.CreateModel(
            name='LearningProgrammeModuleFormative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=20)),
                ('weight', models.PositiveIntegerField()),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formative', to='college.learningprogrammemodule')),
            ],
        ),
        migrations.CreateModel(
            name='LearningProgrammeELOAssessmentCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('elo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_criteria', to='college.learningprogrammeelo')),
            ],
        ),
        migrations.CreateModel(
            name='LearningProgrammeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, upload_to=college.models.update_file_path)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.CharField(default='Yes', max_length=3)),
                ('learning_programme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='college.learningprogramme')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_programme_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearningProgrammeCompetencyBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breakdown', to='college.learningprogrammecompetency')),
            ],
        ),
        migrations.CreateModel(
            name='LearningProgrammeCohortRegistrationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('learning_programme_cohort', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_periods', to='college.learningprogrammecohort')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_periods', to='college.learningprogrammeperiod')),
                ('programme_coordinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programmes', to=settings.AUTH_USER_MODEL)),
                ('summative_procedures_moderators', models.ManyToManyField(related_name='programmes', to='college.moderator')),
            ],
        ),
        migrations.CreateModel(
            name='LearningProgrammeBlockTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_week', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility_type', models.CharField(max_length=3, null=True)),
                ('time_period', models.CharField(choices=[('Night', 'Night'), ('Day', 'Day')], max_length=5)),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_programme_block_template', to='configurable.progarmmeblock')),
                ('learning_programme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_template', to='college.learningprogramme')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_template', to='college.learningprogrammeperiod')),
            ],
            options={
                'ordering': ['academic_week'],
            },
        ),
        migrations.CreateModel(
            name='HealthCareFacilityWard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wards', to='college.healthcarefacility')),
                ('ward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='healthcare_facilities', to='configurable.ward')),
            ],
        ),
        migrations.CreateModel(
            name='HealthCareFacilityLearningProgrammeNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_numbers', models.PositiveIntegerField()),
                ('health_care_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_programme_numbers', to='college.healthcarefacility')),
                ('learning_programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_care_facility_numbers', to='college.learningprogramme')),
            ],
        ),
        migrations.CreateModel(
            name='HealthCareFacilityHOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, null=True)),
                ('first_name', models.CharField(max_length=15, null=True)),
                ('last_name', models.CharField(max_length=15, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('contact', models.CharField(max_length=15, null=True)),
                ('active', models.CharField(default='Yes', max_length=3)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hods', to='college.healthcarefacility')),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_hod', to='configurable.gender')),
                ('race', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_hod', to='configurable.race')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_hod', to=settings.AUTH_USER_MODEL)),
                ('wards', models.ManyToManyField(related_name='hods', to='college.healthcarefacilityward')),
            ],
        ),
        migrations.CreateModel(
            name='HealthCareFacilityDisciplineNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_numbers', models.PositiveIntegerField()),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_numbers', to='configurable.discipline')),
                ('health_care_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_numbers', to='college.healthcarefacility')),
                ('learning_programme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discipline_numbers', to='college.learningprogramme')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('active', models.CharField(default='Yes', max_length=3)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_staff', to='college.healthcarefacility')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='EducationPlanYearSectionWILRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('credits', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('education_plan_year_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wil_requirements', to='college.educationplanyearsection')),
                ('period_wil_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_wil_requirements', to='college.learningprogrammeperiodwilrequirement')),
            ],
        ),
        migrations.CreateModel(
            name='EducationPlanYearSectionWeeks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_of_week', models.DateField()),
                ('end_of_week', models.DateField()),
                ('week_number', models.PositiveIntegerField()),
                ('academic_week_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility_type', models.CharField(default='C', max_length=3, null=True)),
                ('time_period', models.CharField(choices=[('Night', 'Night'), ('Day', 'Day')], max_length=5, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=college.models.update_timetable_path)),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cohort_period_weeks', to='configurable.progarmmeblock')),
                ('education_plan_year_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='college.educationplanyearsection')),
            ],
        ),
        migrations.CreateModel(
            name='EducationPlanYearSectionWeekDaySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_procedure', models.CharField(blank=True, choices=[('Demonstration', 'Demonstration'), ('Practice', 'Practice')], max_length=13, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credits', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_sessions', to='college.educationplanyearsectionweekday')),
                ('lecturers', models.ManyToManyField(related_name='timetable_days', to='college.staff')),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_days', to='college.cohortregistrationperiodmodule')),
                ('procedures', models.ManyToManyField(related_name='timetable_days', to='college.cohortregistrationprocedure')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_days', to='college.learningprogrammeperiodtimetablesession')),
                ('study_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_days', to='college.learningprogrammemodulestudyunit')),
            ],
            options={
                'ordering': ['day'],
            },
        ),
        migrations.AddField(
            model_name='educationplanyearsectionweekday',
            name='education_plan_section_week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='college.educationplanyearsectionweeks'),
        ),
        migrations.AddField(
            model_name='educationplanyear',
            name='cohort_registration_period',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_plan', to='college.learningprogrammecohortregistrationperiod'),
        ),
        migrations.CreateModel(
            name='CohortRegistrationProcedureTaskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('question_type', models.CharField(choices=[('Note', 'Note'), ('Heading', 'Heading'), ('Question', 'Question')], default='Question', max_length=10)),
                ('number', models.CharField(max_length=20)),
                ('penalty', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='college.cohortregistrationprocedure')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='CohortRegistrationProcedureSummativeTaskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('question_type', models.CharField(choices=[('Note', 'Note'), ('Heading', 'Heading'), ('Question', 'Question')], default='Question', max_length=10)),
                ('number', models.CharField(max_length=20)),
                ('penalty', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='college.cohortregistrationproceduresummative')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='cohortregistrationproceduresummative',
            name='cohort_registration_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cohort_period_summative_procedures', to='college.learningprogrammecohortregistrationperiod'),
        ),
        migrations.AddField(
            model_name='cohortregistrationproceduresummative',
            name='procedure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cohort_period_summative_procedures', to='configurable.clinicalprocedurethemetask'),
        ),
        migrations.AddField(
            model_name='cohortregistrationprocedure',
            name='cohort_registration_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cohort_period_procedures', to='college.learningprogrammecohortregistrationperiod'),
        ),
        migrations.AddField(
            model_name='cohortregistrationprocedure',
            name='lecturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedure_lecturer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cohortregistrationprocedure',
            name='lecturer_demonstration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedure_lecturer_demonstration', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cohortregistrationprocedure',
            name='procedure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cohort_period_procedures', to='configurable.clinicalprocedurethemetask'),
        ),
        migrations.CreateModel(
            name='CohortRegistrationPeriodModuleRegisterStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=10)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='college.cohortregistrationperiodmoduleregister')),
            ],
        ),
    ]
