# Generated by Django 4.2.22 on 2025-12-05 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('college', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configurable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohortregistrationperiodmoduleregisterstudents',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_registers', to='students.studentlearningprogrammeregistration'),
        ),
        migrations.AddField(
            model_name='cohortregistrationperiodmoduleregister',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registers', to='college.cohortregistrationperiodmodule'),
        ),
        migrations.AddField(
            model_name='cohortregistrationperiodmoduleregister',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registers', to='college.learningprogrammemodulestudyunit'),
        ),
        migrations.AddField(
            model_name='cohortregistrationperiodmoduleregister',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_registers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cohortregistrationperiodmodulemoderationreportanswers',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_criteria', to='college.learningprogrammeperiodmoderationcriteria'),
        ),
        migrations.AddField(
            model_name='cohortregistrationperiodmodulemoderationreportanswers',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_criteria', to='college.cohortregistrationperiodmodulemoderationreport'),
        ),
        migrations.AddField(
            model_name='cohortregistrationperiodmodulemoderationreportanswers',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_criteria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cohortregistrationperiodmodulemoderationreport',
            name='moderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_report', to='college.moderator'),
        ),
        migrations.AddField(
            model_name='cohortregistrationperiodmodulemoderationreport',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_report', to='college.cohortregistrationperiodmodule'),
        ),
        migrations.AddField(
            model_name='cohortregistrationperiodmoduleformative',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formative', to='college.cohortregistrationperiodmodule'),
        ),
        migrations.AddField(
            model_name='cohortregistrationperiodmodule',
            name='cohort_registration_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='college.learningprogrammecohortregistrationperiod'),
        ),
        migrations.AddField(
            model_name='cohortregistrationperiodmodule',
            name='lecturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_lecturers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cohortregistrationperiodmodule',
            name='moderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='college.moderator'),
        ),
        migrations.AddField(
            model_name='cohortregistrationperiodmodule',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='college.learningprogrammemodule'),
        ),
        migrations.AddField(
            model_name='cohortregistrationperiodeducationplan',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cohort_period', to='configurable.progarmmeblock'),
        ),
        migrations.AddField(
            model_name='cohortregistrationperiodeducationplan',
            name='cohort_registration_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_education_plan', to='college.learningprogrammecohortregistrationperiod'),
        ),
        migrations.AddField(
            model_name='cohortregistrationcompulsoryprocedure',
            name='cohort_registration_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compulsory_procedures', to='college.learningprogrammecohortregistrationperiod'),
        ),
        migrations.AddField(
            model_name='cohortregistrationcompulsoryprocedure',
            name='procedure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compulsory_procedures', to='configurable.clinicalprocedurethemetask'),
        ),
    ]
