# Generated by Django 4.2.22 on 2025-12-05 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import workshops.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('college', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('registration', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('workshop_date', models.DateField()),
                ('workshop_enddate', models.DateField()),
                ('workshop_time', models.TimeField()),
                ('location', models.TextField()),
                ('extra_information', models.TextField()),
                ('file', models.FileField(default='', upload_to=workshops.models.workshop_file_path)),
                ('published', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshops', to='college.collegecampus')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopRSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.CharField(default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvp_workshops', to='students.student')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvp_students', to='workshops.workshop')),
            ],
        ),
        migrations.AddField(
            model_name='workshop',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshops', to='workshops.workshoptype'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshops', to=settings.AUTH_USER_MODEL),
        ),
    ]
