# Generated by Django 4.2.22 on 2025-12-05 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('college', '0001_initial'),
        ('announcements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningprogrammecohortregisteredannouncement',
            name='learning_programme_cohort_registration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='college.learningprogrammecohortregistrationperiod'),
        ),
        migrations.AddField(
            model_name='learningprogrammecohortregisteredannouncement',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements_cohort', to='accounts.role'),
        ),
        migrations.AddField(
            model_name='learningprogrammecohortregisteredannouncement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements_cohort', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learningprogrammecohortannouncement',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements_lp', to='announcements.announcementcategory'),
        ),
        migrations.AddField(
            model_name='learningprogrammecohortannouncement',
            name='learning_programme_cohort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='college.learningprogrammecohort'),
        ),
        migrations.AddField(
            model_name='learningprogrammecohortannouncement',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements_lp', to='accounts.role'),
        ),
        migrations.AddField(
            model_name='learningprogrammecohortannouncement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements_lp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='announcements.announcementcategory'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='accounts.role'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL),
        ),
    ]
