# Generated by Django 4.2.22 on 2025-12-05 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacilityActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility_management.activity')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility_management.facility')),
            ],
        ),
        migrations.CreateModel(
            name='FacilityActivityBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('booking_time_start', models.TimeField()),
                ('booking_time_end', models.TimeField(blank=True, null=True)),
                ('number_of_slots', models.PositiveIntegerField()),
                ('booking_description', models.TextField()),
                ('status', models.CharField(default='Requested', max_length=10)),
                ('status_reason', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('facility_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='facility_management.facilityactivity')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='accounts.role')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='facility',
            name='activities',
            field=models.ManyToManyField(related_name='facilities', through='facility_management.FacilityActivity', to='facility_management.activity'),
        ),
        migrations.AddField(
            model_name='facility',
            name='admins',
            field=models.ManyToManyField(related_name='facility_administrator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facility',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_facilities', to=settings.AUTH_USER_MODEL),
        ),
    ]
