from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(City)
admin.site.register(Country)
admin.site.register(Province)
admin.site.register(Municipality)
admin.site.register(Language)
admin.site.register(Suburb)
admin.site.register(EconomicStatus)
admin.site.register(Gender)
admin.site.register(Disability)
admin.site.register(EmploymentEconomicStatus)
admin.site.register(Race)
admin.site.register(ResidentialStatus)
admin.site.register(TypeOfID)
admin.site.register(StructureStatusID)
admin.site.register(Industry)
admin.site.register(QuestionType)
admin.site.register(QuestionTypeOptions)
admin.site.register(AlternateIDType)
admin.site.register(Nationality)
admin.site.register(SchoolCodes)
admin.site.register(NQFLevel)
