"""
Django settings for django_nursing project.

Generated by 'django-admin startproject' using Django 4.2.22.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import dotenv
from pathlib import Path
import pymysql

dotenv.load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATES_DIR = os.path.join(BASE_DIR,'templates')
STATIC_DIR = os.path.join(BASE_DIR,"static")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jpuwo@0g*083x1$p$p(rs_=s_!yb@xd&)^lvj9n#*ecl=g5t-2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

INTERNAL_IPS = [
    "127.0.0.1",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'drf_multiple_model',
    'debug_toolbar',
    'storages',
    'administration',
    'accounts',
    'college',
    'adverts',
    'funder',
    'blog',
    'workshops',
    'issuetracker',
    'configurable',
    'students',
    'events',
    'todo',
    'api',
    'appointments',
    'libraryms',
    'announcements',
    'facility_management',
    'resource_management',
]

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    'bugsnag.django.middleware.BugsnagMiddleware',
    'django.middleware.security.SecurityMiddleware',    
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_auto_logout.middleware.auto_logout',#Auto logout
    "django_htmx.middleware.HtmxMiddleware",
    'django_nursing.middleware.LoginAttemptMiddleware',
]

AUTHENTICATION_BACKENDS = [
    # AxesStandaloneBackend should be the first backend in the AUTHENTICATION_BACKENDS list.

    #'axes.backends.AxesStandaloneBackend',

    # Django ModelBackend is the default authentication backend.

    'django.contrib.auth.backends.ModelBackend',
]

ROOT_URLCONF = 'django_nursing.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'django_auto_logout.context_processors.auto_logout_client',#Auto logout
                'django_nursing.context_processors.menu_programmes',
                'django_nursing.context_processors.menu_roles',
                'django_nursing.context_processors.menu_fetch_student',
                'django_nursing.context_processors.menu_fetch_wards',
                'django_nursing.context_processors.menu_current_date',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_nursing.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        # MySQL database engine class.
        'ENGINE': 'django.db.backends.mysql',
        # MySQL database host ip.
        'HOST': '102.130.121.37',
        # port number.
        'PORT': '3306',
        # database name.
        'NAME': 'sims_nursing',
        # user name.
        #'USER': 'wilmsaho_mark',
        'USER': 'sims_ahc',
        # password
        'PASSWORD': os.getenv('DB_PASSWORD'),
        # connect options
        'OPTIONS': {'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",},
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Johannesburg'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    STATIC_DIR,
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGIN_REDIRECT_URL = '/accounts/role_lookup/'
LOGOUT_REDIRECT_URL = '/accounts/login/user'
LOGIN_URL = '/accounts/login/user'

AUTH_USER_MODEL = 'accounts.User'

AWS_ACCESS_KEY_ID = 'AKIA6D4U55GBUHIRAKX7'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'bms-nursing-media'
AWS_S3_CUSTOM_DOMAIN = '%s.s3.eu-west-1.amazonaws.com' % AWS_STORAGE_BUCKET_NAME
AWS_DEFAULT_ACL = 'public-read'

AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}

AWS_LOCATION = 'static'
AWS_MEDIA_LOCATION = 'media'
STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
STATIC_URL = "https://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, AWS_LOCATION)
MEDIA_URL = "https://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, AWS_MEDIA_LOCATION)

DEFAULT_FILE_STORAGE = 'django_nursing.storage_backends.MediaStorage'

TIME= 100*60
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'
SESSION_EXPIRE_AT_BROWSER_CLOSE= True
SESSION_COOKIE_AGE = TIME
SESSION_IDLE_TIMEOUT = TIME

#AUTO LOGOUT
AUTO_LOGOUT = {
    'IDLE_TIME': 1800,
    'MESSAGE': 'The session has expired. Please login again to continue.',
    'REDIRECT_TO_LOGIN_IMMEDIATELY': True,
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

### EMAIL SECTION

EMAIL_HOST = 'nursing.elevatelearn.co.za'
EMAIL_HOST_USER = 'nursing@elevatelearn.co.za'
EMAIL_HOST_PASSWORD = '+x%pDF)lsI5--JJm'
DEFAULT_FROM_EMAIL = 'nursing@elevatelearn.co.za'
SERVER_EMAIL = 'mail.elevatelearn.co.za '
EMAIL_PORT = 587
EMAIL_USE_TLS = False

#recaptcha keys

RECAPTCHA_PUBLIC_KEY = os.getenv('RECAPTCHA_PUBLIC_KEY')
RECAPTCHA_PRIVATE_KEY = os.getenv('RECAPTCHA_PRIVATE_KEY')

#axes configuration settings

AXES_FAILURE_LIMIT: 5 #How many times a user can fail a login

AXES_COOLOFF_TIME: 1 # Wait 1 hours before attempting to login again

AXES_RESET_ON_SUCCESS = True # Reset failed login attempts

AXES_LOCKOUT_TEMPLATE = 'accounts/account-locked.html'

ADMINS = [("Mark", "mmuwanguzi@gmail.com"), ("Mark", "mark@mytech-dev.com")]



# In settings.py, set login rate limits and lockout settings
LOGIN_RATE_LIMIT = '5/m'
LOGIN_FAILS_LIMIT = 5
LOGIN_FAILS_TIMEOUT = 300  # 5 minutes

# In settings.py, configure logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'failed_login': {
            'level': 'DEBUG',
            'class': 'django.utils.log.AdminEmailHandler',
        },
    },
    'loggers': {
        'django.security': {
            'handlers': ['failed_login'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}


'''
Bugsnag to view errors and performance monitoring
'''

BUGSNAG = {
    'api_key': '7cb9ce9226aab1a4237b2145a6415c8f',
    #'project_root': '/path/to/your/app',
}


# Deploymnet settings

# Protection against XSS attacks

'''SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

# CSRF Protection

SESSION_COOKIE_SECURE = True
CSRF_COOKIES_SECURE = True'''
'''
# SSL Redirect

SECURE_SSL_REDIRECT = True
'''

#Enable HSTS

'''SECURE_HSTS_SECONDS = 86400

SECURE_HSTS_PRELOAD = True

SECURE_HSTS_INCLUDE_SUBDOMAINS = True'''

# look into a csp (Content Security Policy)'''

DEBUG_TOOLBAR_PANELS = [
    'debug_toolbar.panels.history.HistoryPanel',
    'debug_toolbar.panels.versions.VersionsPanel',
    'debug_toolbar.panels.timer.TimerPanel',
    'debug_toolbar.panels.settings.SettingsPanel',
    'debug_toolbar.panels.headers.HeadersPanel',
    'debug_toolbar.panels.request.RequestPanel',
    'debug_toolbar.panels.sql.SQLPanel',
    'debug_toolbar.panels.staticfiles.StaticFilesPanel',
    'debug_toolbar.panels.templates.TemplatesPanel',
    'debug_toolbar.panels.cache.CachePanel',
    'debug_toolbar.panels.signals.SignalsPanel',
    'debug_toolbar.panels.redirects.RedirectsPanel',
    'debug_toolbar.panels.profiling.ProfilingPanel',
]


REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS':'drf_spectacular.openapi.AutoSchema'
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}